INSERT INTO ACCOUNT_TYPE(ID, ACCOUNT_NAME, ACCOUNT_TYPE, CURRENCY) VALUES (1, 'SGSavings726', 'Savings', 'AUD');

INSERT INTO CUSTOMER( ID, CUSTOMER_ID, FULL_NAME) VALUES (1, '10001', 'Sam Hat');
INSERT INTO ACCOUNT (ID ,CUSTOMER_ID, BALANCE_DATA , OPENING_AVAILABLE_BALANCE, ACCOUNT_TYPE_ID, ACCOUNT_NUMBER) VALUES (1, 1, 1500.00, 1200.00, 1, '1000001');
INSERT INTO TRANSACTION (ID ,ACCOUNT_ID, AMOUNT , CREDIT_DEBIT) VALUES (1, 1, 50.00, 'Y');
INSERT INTO TRANSACTION (ID ,ACCOUNT_ID, AMOUNT , CREDIT_DEBIT) VALUES (2, 1, 20.00, 'Y');
INSERT INTO TRANSACTION (ID ,ACCOUNT_ID, AMOUNT , CREDIT_DEBIT) VALUES (3, 1, 10.00, 'Y');
INSERT INTO TRANSACTION (ID ,ACCOUNT_ID, AMOUNT , CREDIT_DEBIT) VALUES (4, 1, 5.00, 'N');
