CREATE TABLE CUSTOMER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID BIGINT,
  FULL_NAME VARCHAR(200),
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID)
);
CREATE TABLE ACCOUNT_TYPE(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_NAME VARCHAR(200),
  ACCOUNT_TYPE VARCHAR(40),
  CURRENCY VARCHAR(10),
  CONSTRAINT PK_ACCOUNT_TYPE PRIMARY KEY (ID)
);
CREATE TABLE ACCOUNT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID BIGINT,
  BALANCE_DATA DECIMAL(21,2),
  ACCOUNT_NUMBER VARCHAR(40),
  OPENING_AVAILABLE_BALANCE  DECIMAL(21,2),
  ACCOUNT_TYPE_ID  BIGINT,
  CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID),
  CONSTRAINT FK_ACCOUNT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
  CONSTRAINT FK_ACCOUNT_ACCOUNT_TYPE FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACCOUNT_TYPE (ID)
);
CREATE TABLE TRANSACTION(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_ID BIGINT,
  TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  AMOUNT DECIMAL(21,2),
  CREDIT_DEBIT CHAR(1) NOT NULL DEFAULT 'N',
  CONSTRAINT PK_TRANSACTION PRIMARY KEY (ID),
  CONSTRAINT FK_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID)
);
